package com.bencodez.votingplugin.votelog;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.util.Collections;
import java.util.List;
import java.util.UUID;

import com.bencodez.simpleapi.sql.DataType;
import com.bencodez.simpleapi.sql.mysql.AbstractSqlTable;
import com.bencodez.simpleapi.sql.mysql.DbType;
import com.bencodez.simpleapi.sql.mysql.MySQL;
import com.bencodez.simpleapi.sql.mysql.config.MysqlConfig;
import com.bencodez.simpleapi.sql.mysql.queries.Query;

/**
 * Vote log table usable from BOTH proxy and backend.
 *
 * LOG ONLY table (not the offline queue).
 *
 * Records the "main reward triggers" (not every command executed).
 *
 * Columns: - id (auto increment primary key) - vote_id (correlation id / vote
 * uuid; NOT UNIQUE; may repeat for other events) - vote_time (LONG millis,
 * explicit time event happened) - event (VOTE_RECEIVED default; includes
 * reward-trigger events) - context (which reward/config fired + any extra info
 * like TimeType, ex: "TopVoter:MONTH") - status (IMMEDIATE/CACHED) -
 * cached_total (int, proxy only snapshot; can be 0 on backend) - service -
 * server (server name, provided by getServerName()) - player_uuid - player_name
 *
 * NOTE: - This table is NOT meant to use AbstractSqlTable's primary key caching
 * (it would be huge). We override primary key caches and containsKey behaviors
 * to avoid loading/caching all rows. - INSERTs use PreparedStatements (works on
 * MySQL/MariaDB/Postgres).
 */
public abstract class VoteLogMysqlTable extends AbstractSqlTable {

	public enum VoteLogEvent {
		// Core
		VOTE_RECEIVED,

		// Reward triggers
		ALL_SITES_REWARD, ALMOST_ALL_SITES_REWARD, FIRST_VOTE_REWARD, FIRST_VOTE_TODAY_REWARD, CUMULATIVE_REWARD,
		MILESTONE_REWARD, VOTE_STREAK_REWARD, TOP_VOTER_REWARD,

		// VoteShop
		VOTESHOP_PURCHASE
	}

	public enum VoteLogStatus {
		IMMEDIATE, CACHED
	}

	private final boolean debugEnabled;

	// Kept for compatibility with your existing call sites / style
	public abstract void logSevere1(String string);

	public abstract void logInfo1(String string);

	public abstract void debug1(SQLException e);

	/**
	 * Server name to store in the vote log for ALL writes. (Typically:
	 * plugin.getOptions().getServer())
	 *
	 * @return server name (may be blank)
	 */
	public abstract String getServerName();

	// ---- Constructors ----

	public VoteLogMysqlTable(String baseTableName, MysqlConfig config, boolean debug) {
		super(baseTableName, config, debug, true);
		this.debugEnabled = debug;
		ensureColumnsAndIndexes();
	}

	public VoteLogMysqlTable(String baseTableName, MySQL existingMysql, MysqlConfig config, boolean debug) {
		super(resolveName(baseTableName, config), existingMysql, resolveType(config), true);
		this.debugEnabled = debug;
		ensureColumnsAndIndexes();
	}

	private static String resolveName(String baseTableName, MysqlConfig config) {
		String resolved = baseTableName;
		if (config != null) {
			if (config.hasTableNameSet()) {
				resolved = config.getTableName();
			}
			if (config.getTablePrefix() != null) {
				resolved = config.getTablePrefix() + resolved;
			}
		}
		return resolved;
	}

	private static DbType resolveType(MysqlConfig config) {
		if (config == null || config.getDbType() == null) {
			return DbType.MYSQL;
		}
		return config.getDbType();
	}

	// ---- AbstractSqlTable required hooks ----

	/**
	 * We intentionally DO NOT use a real primary key for caching in this log table.
	 * Returning "id" keeps queries sane if anything calls containsKeyQuery, but we
	 * override caching methods to avoid loading it.
	 */
	@Override
	public String getPrimaryKeyColumn() {
		return "id";
	}

	@Override
	public String buildCreateTableSql(DbType dbType) {
		// Minimal create. Columns/types are normalized in ensureColumnsAndIndexes().
		if (dbType == DbType.POSTGRESQL) {
			return "CREATE TABLE IF NOT EXISTS " + qi(getTableName()) + " (" + qi("id")
					+ " BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " + qi("vote_id") + " VARCHAR(36) NULL"
					+ ");";
		}

		// MySQL/MariaDB
		return "CREATE TABLE IF NOT EXISTS " + qi(getTableName()) + " (" + qi("id")
				+ " BIGINT NOT NULL AUTO_INCREMENT, " + qi("vote_id") + " VARCHAR(36) NULL, " + "PRIMARY KEY ("
				+ qi("id") + ")" + ");";
	}

	@Override
	public void logSevere(String msg) {
		logSevere1(msg);
	}

	@Override
	public void logInfo(String msg) {
		logInfo1(msg);
	}

	@Override
	public void debug(Throwable t) {
		if (!debugEnabled) {
			return;
		}
		if (t instanceof SQLException) {
			debug1((SQLException) t);
		} else {
			t.printStackTrace();
		}
	}

	@Override
	public void debug(String messasge) {
		if (debugEnabled) {
			logInfo1("MYSQL DEBUG: " + messasge);
		}
	}

	// ---- Disable AbstractSqlTable row-key caching for this log table ----

	@Override
	public List<String> getPrimaryKeysQuery() {
		// Don't load/cached keys for a log table (could be millions of rows)
		return java.util.Collections.emptyList();
	}

	@Override
	public boolean containsKey(String key) {
		// Not meaningful for this log table
		return false;
	}

	@Override
	public boolean containsKeyQuery(String key) {
		// Not meaningful for this log table
		return false;
	}

	// ---- Schema ensure ----

	private final Object initLock = new Object();

	private void ensureColumnsAndIndexes() {
		synchronized (initLock) {
			// Ensure table exists (deferInit=true)
			init();

			// Columns
			checkColumn("vote_id", DataType.STRING);
			checkColumn("vote_time", DataType.INTEGER);
			checkColumn("player_uuid", DataType.STRING);
			checkColumn("player_name", DataType.STRING);
			checkColumn("service", DataType.STRING);
			checkColumn("server", DataType.STRING);
			checkColumn("event", DataType.STRING);
			checkColumn("context", DataType.STRING);
			checkColumn("status", DataType.STRING);
			checkColumn("cached_total", DataType.INTEGER);

			// Normalize types (DbType-aware)
			alterColumnType("vote_id", "VARCHAR(36) NULL");
			alterColumnType("vote_time", "BIGINT NOT NULL DEFAULT '0'");
			alterColumnType("player_uuid", (dbType == DbType.POSTGRESQL) ? "UUID" : "VARCHAR(37)");
			alterColumnType("player_name", "VARCHAR(16)");
			alterColumnType("service", "VARCHAR(64)");
			alterColumnType("server", "VARCHAR(64)");
			alterColumnType("event", "VARCHAR(64) NOT NULL");
			alterColumnType("context", "VARCHAR(255) NULL");
			alterColumnType("status", "VARCHAR(16)");
			alterColumnType("cached_total", "INT NOT NULL DEFAULT '0'");

			// Defaults (Postgres needs SET DEFAULT separate)
			ensureDefault("vote_time", "0");
			ensureDefault("event", "'" + VoteLogEvent.VOTE_RECEIVED.name() + "'");
			ensureDefault("cached_total", "0");

			// Indexes
			createIndexIfMissing("idx_vote_time", new String[] { "vote_time" });
			createIndexIfMissing("idx_uuid_time", new String[] { "player_uuid", "vote_time" });
			createIndexIfMissing("idx_service_time", new String[] { "service", "vote_time" });
			createIndexIfMissing("idx_server_time", new String[] { "server", "vote_time" });
			createIndexIfMissing("idx_status_time", new String[] { "status", "vote_time" });
			createIndexIfMissing("idx_event_time", new String[] { "event", "vote_time" });
			createIndexIfMissing("idx_context_time", new String[] { "context", "vote_time" });
			createIndexIfMissing("idx_event_context_time", new String[] { "event", "context", "vote_time" });

			createIndexIfMissing("idx_vote_id", new String[] { "vote_id" });
			createIndexIfMissing("idx_vote_id_time", new String[] { "vote_id", "vote_time" });
		}
	}

	private void ensureDefault(String column, String defaultSqlLiteral) {
		if (dbType != DbType.POSTGRESQL) {
			// MySQL default is handled via MODIFY in alterColumnType above (best effort).
			return;
		}

		String sql = "ALTER TABLE " + qi(getTableName()) + " ALTER COLUMN " + qi(column) + " SET DEFAULT "
				+ defaultSqlLiteral + ";";
		try {
			new Query(mysql, sql).executeUpdateAsync();
		} catch (SQLException e) {
			debug(e);
		}
	}

	private void createIndexIfMissing(String indexName, String[] cols) {
		if (indexName == null || indexName.isEmpty() || cols == null || cols.length == 0) {
			return;
		}

		if (hasIndex(indexName)) {
			return;
		}

		StringBuilder colsSql = new StringBuilder();
		colsSql.append("(");
		for (int i = 0; i < cols.length; i++) {
			if (i > 0) {
				colsSql.append(",");
			}
			colsSql.append(qi(cols[i]));
		}
		colsSql.append(")");

		String sql;
		if (dbType == DbType.POSTGRESQL) {
			sql = "CREATE INDEX IF NOT EXISTS " + qi(indexName) + " ON " + qi(getTableName()) + " " + colsSql + ";";
		} else {
			sql = "CREATE INDEX " + qi(indexName) + " ON " + qi(getTableName()) + " " + colsSql + ";";
		}

		try {
			new Query(mysql, sql).executeUpdate();
		} catch (SQLException e) {
			// MySQL duplicate name -> ignore; Postgres IF NOT EXISTS already safe
			if (isDuplicateIndexName(e)) {
				return;
			}
			debug(e);
		}
	}

	private boolean hasIndex(String indexName) {
		if (dbType == DbType.POSTGRESQL) {
			String sql = "SELECT 1 FROM pg_indexes WHERE schemaname = current_schema() AND tablename = ? AND indexname = ?;";
			try (Connection conn = mysql.getConnectionManager().getConnection();
					PreparedStatement ps = conn.prepareStatement(sql)) {
				ps.setString(1, getTableName());
				ps.setString(2, indexName);
				try (ResultSet rs = ps.executeQuery()) {
					return rs.next();
				}
			} catch (SQLException e) {
				debug(e);
				return true; // be conservative
			}
		}

		String sql = "SHOW INDEX FROM " + qi(getTableName()) + " WHERE Key_name = ?;";
		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {
			ps.setString(1, indexName);
			try (ResultSet rs = ps.executeQuery()) {
				return rs.next();
			}
		} catch (SQLException e) {
			debug(e);
			return true; // be conservative
		}
	}

	private static boolean isDuplicateIndexName(SQLException e) {
		return e != null && e.getErrorCode() == 1061; // MySQL: Duplicate key name
	}

	// ---- Utility ----

	private static String safeStr(String s) {
		return s == null ? "" : s;
	}

	private String resolveServerName() {
		try {
			return safeStr(getServerName());
		} catch (Exception e) {
			return "";
		}
	}

	public static String withTimeType(String baseContext, String timeType) {
		baseContext = safeStr(baseContext);
		timeType = safeStr(timeType);
		if (baseContext.isEmpty()) {
			return timeType.isEmpty() ? "" : timeType;
		}
		if (timeType.isEmpty()) {
			return baseContext;
		}
		return baseContext + ":" + timeType;
	}

	private static String limit(String s, int max) {
		if (s == null) {
			return "";
		}
		if (s.length() <= max) {
			return s;
		}
		return s.substring(0, max);
	}

	// ---- VoteShop helpers ----

	public static String voteShopContext(String identifier, int cost) {
		identifier = safeStr(identifier);

		StringBuilder sb = new StringBuilder();
		sb.append("VShop:").append(identifier.replace(":", "_")).append(":cost=").append(cost);

		return limit(sb.toString(), 240);
	}

	// ---- INSERT (Postgres-safe, and closes connections reliably) ----

	private void insertLogRow(String voteId, long timeMillis, String playerUuid, String playerName, String service,
			String server, VoteLogEvent event, String context, VoteLogStatus status, int cachedTotal) {

		String sql = "INSERT INTO " + qi(getTableName())
				+ " (vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total)"
				+ " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);";

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			// vote_id
			if (voteId == null || voteId.isEmpty()) {
				ps.setNull(1, Types.VARCHAR);
			} else {
				ps.setString(1, voteId);
			}

			ps.setLong(2, timeMillis);

			// player_uuid: support UUID type on Postgres
			if (dbType == DbType.POSTGRESQL) {
				try {
					UUID u = (playerUuid == null || playerUuid.isEmpty()) ? null : UUID.fromString(playerUuid);
					if (u == null) {
						ps.setNull(3, Types.OTHER);
					} else {
						ps.setObject(3, u);
					}
				} catch (IllegalArgumentException ex) {
					ps.setNull(3, Types.OTHER);
				}
			} else {
				ps.setString(3, safeStr(playerUuid));
			}

			ps.setString(4, safeStr(playerName));
			ps.setString(5, safeStr(service));
			ps.setString(6, safeStr(server));
			ps.setString(7, (event == null ? VoteLogEvent.VOTE_RECEIVED.name() : event.name()));

			if (context == null || context.isEmpty()) {
				ps.setNull(8, Types.VARCHAR);
			} else {
				ps.setString(8, context);
			}

			ps.setString(9, (status == null ? VoteLogStatus.IMMEDIATE.name() : status.name()));
			ps.setInt(10, cachedTotal);

			ps.executeUpdate();
		} catch (SQLException e) {
			debug(e);
		}
	}

	// ---- Public logging API ----

	public void logVoteShopPurchase(String playerUuid, String playerName, long timeMillis, String identifier,
			int cost) {
		String ctx = voteShopContext(identifier, cost);
		logEvent(null, VoteLogEvent.VOTESHOP_PURCHASE, ctx, VoteLogStatus.IMMEDIATE, "", playerUuid, playerName,
				timeMillis, 0);
	}

	public String logVote(UUID voteUUID, VoteLogStatus status, String service, String playerUuid, String playerName,
			long voteTimeMillis, int proxyCachedTotal) {

		return logEvent(voteUUID, VoteLogEvent.VOTE_RECEIVED, null, status, service, playerUuid, playerName,
				voteTimeMillis, proxyCachedTotal);
	}

	public String logEvent(UUID voteUUID, VoteLogEvent event, String context, VoteLogStatus status, String service,
			String playerUuid, String playerName, long timeMillis, int proxyCachedTotal) {

		String voteId = voteUUID != null ? voteUUID.toString() : null;

		if (event == null) {
			event = VoteLogEvent.VOTE_RECEIVED;
		}
		if (status == null) {
			status = VoteLogStatus.IMMEDIATE;
		}
		if (service == null) {
			service = "";
		}

		String server = resolveServerName();
		insertLogRow(voteId, timeMillis, playerUuid, playerName, service, server, event, context, status,
				proxyCachedTotal);

		return voteId;
	}

	public String logEvent(UUID voteUUID, VoteLogEvent event, String context, String playerUuid, String playerName,
			long timeMillis) {

		String voteId = voteUUID != null ? voteUUID.toString() : null;

		if (event == null) {
			event = VoteLogEvent.VOTE_RECEIVED;
		}

		String server = resolveServerName();

		// Keep stable/defaults for these calls
		insertLogRow(voteId, timeMillis, playerUuid, playerName, "", server, event, context, null, 0);

		return voteId;
	}

	public String logEventNow(UUID voteUUID, VoteLogEvent event, String context, String playerUuid, String playerName) {
		return logEvent(voteUUID, event, context, playerUuid, playerName, System.currentTimeMillis());
	}

	public void logAllSitesReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String rewardKey) {
		logEvent(voteUUID, VoteLogEvent.ALL_SITES_REWARD, safeStr(rewardKey), playerUuid, playerName, timeMillis);
	}

	public void logAlmostAllSitesReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String rewardKey) {
		logEvent(voteUUID, VoteLogEvent.ALMOST_ALL_SITES_REWARD, safeStr(rewardKey), playerUuid, playerName,
				timeMillis);
	}

	public void logFirstVoteReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String rewardKey) {
		logEvent(voteUUID, VoteLogEvent.FIRST_VOTE_REWARD, safeStr(rewardKey), playerUuid, playerName, timeMillis);
	}

	public void logFirstVoteTodayReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String rewardKey) {
		logEvent(voteUUID, VoteLogEvent.FIRST_VOTE_TODAY_REWARD, safeStr(rewardKey), playerUuid, playerName,
				timeMillis);
	}

	public void logCumulativeReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String cumulativeKeyWithTimeType) {
		logEvent(voteUUID, VoteLogEvent.CUMULATIVE_REWARD, safeStr(cumulativeKeyWithTimeType), playerUuid, playerName,
				timeMillis);
	}

	public void logMilestoneReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String milestoneKeyWithTimeType) {
		logEvent(voteUUID, VoteLogEvent.MILESTONE_REWARD, safeStr(milestoneKeyWithTimeType), playerUuid, playerName,
				timeMillis);
	}

	public void logVoteStreakReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String streakKeyWithTimeType) {
		logEvent(voteUUID, VoteLogEvent.VOTE_STREAK_REWARD, safeStr(streakKeyWithTimeType), playerUuid, playerName,
				timeMillis);
	}

	public void logTopVoterReward(UUID voteUUID, String playerUuid, String playerName, long timeMillis,
			String topVoterKeyWithTimeType) {
		logEvent(voteUUID, VoteLogEvent.TOP_VOTER_REWARD, safeStr(topVoterKeyWithTimeType), playerUuid, playerName,
				timeMillis);
	}

	// ---- Purge ----

	public void purgeOlderThanDays(int days, int batchSize) {
		if (days <= 0) {
			return;
		}
		if (batchSize <= 0) {
			batchSize = 5000;
		}

		long cutoff = System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L);

		String sql;
		if (dbType == DbType.POSTGRESQL) {
			// Postgres has no LIMIT in DELETE directly; use ctid batch
			sql = "DELETE FROM " + qi(getTableName()) + " WHERE ctid IN (SELECT ctid FROM " + qi(getTableName())
					+ " WHERE " + qi("vote_time") + " < ? LIMIT " + batchSize + ");";
		} else {
			sql = "DELETE FROM " + qi(getTableName()) + " WHERE " + qi("vote_time") + " < ? LIMIT " + batchSize + ";";
		}

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {
			ps.setLong(1, cutoff);
			ps.executeUpdate();
		} catch (SQLException e) {
			debug(e);
		}
	}

	// ---- Queries ----

	public List<String> getDistinctServices(int days, int limit) {
		if (limit <= 0) {
			limit = 45;
		}

		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT DISTINCT service FROM " + qi(getTableName())
				+ " WHERE service IS NOT NULL AND service != '' " + (useCutoff ? "AND vote_time >= ? " : "")
				+ "ORDER BY service ASC LIMIT " + limit + ";";

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			if (useCutoff) {
				ps.setLong(1, cutoff);
			}

			try (ResultSet rs = ps.executeQuery()) {
				List<String> out = new java.util.ArrayList<>();
				while (rs.next()) {
					out.add(rs.getString("service"));
				}
				return out;
			}
		} catch (SQLException e) {
			debug(e);
			return java.util.Collections.emptyList();
		}
	}

	public List<VoteLogEntry> getRecentAll(int days, int limit) {
		if (limit <= 0) {
			limit = 10;
		}

		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " " + (useCutoff ? "WHERE vote_time >= ? " : "")
				+ "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (useCutoff) {
			return query(sql, new Object[] { cutoff });
		}
		return query(sql, new Object[] {});
	}

	public List<VoteLogEntry> getRecentByEvent(VoteLogEvent event, int days, int limit) {
		if (event == null) {
			return (days > 0) ? getRecentAll(days, limit) : getRecent(limit);
		}
		if (limit <= 0) {
			limit = 10;
		}

		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE event=? " + (useCutoff ? "AND vote_time >= ? " : "")
				+ "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (useCutoff) {
			return query(sql, new Object[] { event.name(), cutoff });
		}
		return query(sql, new Object[] { event.name() });
	}

	public List<VoteLogEntry> getRecent(int days, VoteLogEvent eventFilter, int limit) {
		if (limit <= 0) {
			limit = 10;
		}

		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE 1=1 " + (eventFilter != null ? "AND event=? " : "")
				+ (useCutoff ? "AND vote_time >= ? " : "") + "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (eventFilter != null && useCutoff) {
			return query(sql, new Object[] { eventFilter.name(), cutoff });
		} else if (eventFilter != null) {
			return query(sql, new Object[] { eventFilter.name() });
		} else if (useCutoff) {
			return query(sql, new Object[] { cutoff });
		}
		return query(sql, new Object[] {});
	}

	public VoteLogEntry getByVoteId(String voteId) {
		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE vote_id=? ORDER BY vote_time DESC, id DESC LIMIT 1;";
		List<VoteLogEntry> rows = query(sql, new Object[] { voteId });
		return rows.isEmpty() ? null : rows.get(0);
	}

	public List<VoteLogEntry> getByVoteIdAll(String voteId, int days, int limit) {
		if (limit <= 0) {
			limit = 10;
		}
		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE vote_id=? " + (useCutoff ? "AND vote_time >= ? " : "")
				+ "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (useCutoff) {
			return query(sql, new Object[] { voteId, cutoff });
		}
		return query(sql, new Object[] { voteId });
	}

	public List<VoteLogEntry> getRecent(int limit) {
		if (limit <= 0) {
			limit = 10;
		}
		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";
		return query(sql, new Object[] {});
	}

	public List<VoteLogEntry> getByService(String service, int days, int limit) {
		return getByService(service, null, days, limit);
	}

	public List<VoteLogEntry> getByServiceVotesOnly(String service, int days, int limit) {
		return getByService(service, VoteLogEvent.VOTE_RECEIVED, days, limit);
	}

	public List<VoteLogEntry> getByService(String service, VoteLogEvent event, int days, int limit) {
		if (limit <= 0) {
			limit = 10;
		}
		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE service=? " + (event != null ? "AND event=? " : "")
				+ (useCutoff ? "AND vote_time >= ? " : "") + "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (event != null && useCutoff) {
			return query(sql, new Object[] { service, event.name(), cutoff });
		} else if (event != null) {
			return query(sql, new Object[] { service, event.name() });
		} else if (useCutoff) {
			return query(sql, new Object[] { service, cutoff });
		}
		return query(sql, new Object[] { service });
	}

	public List<VoteLogEntry> getByPlayerName(String playerName, int days, int limit) {
		return getByPlayerName(playerName, null, days, limit);
	}

	public List<VoteLogEntry> getByPlayerNameVotesOnly(String playerName, int days, int limit) {
		return getByPlayerName(playerName, VoteLogEvent.VOTE_RECEIVED, days, limit);
	}

	public List<VoteLogEntry> getByPlayerName(String playerName, VoteLogEvent event, int days, int limit) {
		if (limit <= 0) {
			limit = 10;
		}
		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT vote_id, vote_time, player_uuid, player_name, service, server, event, context, status, cached_total "
				+ "FROM " + qi(getTableName()) + " WHERE player_name=? " + (event != null ? "AND event=? " : "")
				+ (useCutoff ? "AND vote_time >= ? " : "") + "ORDER BY vote_time DESC, id DESC LIMIT " + limit + ";";

		if (event != null && useCutoff) {
			return query(sql, new Object[] { playerName, event.name(), cutoff });
		} else if (event != null) {
			return query(sql, new Object[] { playerName, event.name() });
		} else if (useCutoff) {
			return query(sql, new Object[] { playerName, cutoff });
		}
		return query(sql, new Object[] { playerName });
	}

	public VoteLogCounts getCounts(int days) {
		return getCounts(days, VoteLogEvent.VOTE_RECEIVED);
	}

	public VoteLogCounts getCounts(int days, VoteLogEvent eventFilter) {
		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		// SUM(status='IMMEDIATE') is MySQL-ish; use CASE for portability
		String sql = "SELECT " + "COUNT(*) AS total, "
				+ "SUM(CASE WHEN status='IMMEDIATE' THEN 1 ELSE 0 END) AS immediate, "
				+ "SUM(CASE WHEN status='CACHED' THEN 1 ELSE 0 END) AS cached " + "FROM " + qi(getTableName())
				+ " WHERE 1=1 " + (eventFilter != null ? "AND event=? " : "") + (useCutoff ? "AND vote_time >= ? " : "")
				+ ";";

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			int idx = 1;
			if (eventFilter != null) {
				ps.setString(idx++, eventFilter.name());
			}
			if (useCutoff) {
				ps.setLong(idx++, cutoff);
			}

			try (ResultSet rs = ps.executeQuery()) {
				if (rs.next()) {
					long total = rs.getLong("total");
					long immediate = rs.getLong("immediate");
					long cached = rs.getLong("cached");
					return new VoteLogCounts(total, immediate, cached);
				}
			}
		} catch (SQLException e) {
			debug(e);
		}

		return new VoteLogCounts(0, 0, 0);
	}

	public long getUniqueVoters(int days) {
		return getUniqueVoters(days, VoteLogEvent.VOTE_RECEIVED);
	}

	public long getUniqueVoters(int days, VoteLogEvent eventFilter) {
		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT COUNT(DISTINCT player_uuid) AS uniques " + "FROM " + qi(getTableName()) + " WHERE 1=1 "
				+ (eventFilter != null ? "AND event=? " : "") + (useCutoff ? "AND vote_time >= ? " : "") + ";";

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			int idx = 1;
			if (eventFilter != null) {
				ps.setString(idx++, eventFilter.name());
			}
			if (useCutoff) {
				ps.setLong(idx++, cutoff);
			}

			try (ResultSet rs = ps.executeQuery()) {
				if (rs.next()) {
					return rs.getLong("uniques");
				}
			}
		} catch (SQLException e) {
			debug(e);
		}
		return 0;
	}

	public List<ServiceCount> getTopServices(int days, int limit) {
		return getTopServices(days, limit, VoteLogEvent.VOTE_RECEIVED);
	}

	public List<ServiceCount> getTopServices(int days, int limit, VoteLogEvent eventFilter) {
		if (limit <= 0) {
			limit = 10;
		}

		boolean useCutoff = days > 0;
		long cutoff = useCutoff ? System.currentTimeMillis() - (days * 24L * 60L * 60L * 1000L) : 0;

		String sql = "SELECT service, COUNT(*) AS votes " + "FROM " + qi(getTableName()) + " WHERE 1=1 "
				+ (eventFilter != null ? "AND event=? " : "") + (useCutoff ? "AND vote_time >= ? " : "")
				+ "GROUP BY service " + "ORDER BY votes DESC " + "LIMIT " + limit + ";";

		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			int idx = 1;
			if (eventFilter != null) {
				ps.setString(idx++, eventFilter.name());
			}
			if (useCutoff) {
				ps.setLong(idx++, cutoff);
			}

			ResultSet rs = ps.executeQuery();
			List<ServiceCount> out = Collections.synchronizedList(new java.util.ArrayList<>());
			while (rs.next()) {
				out.add(new ServiceCount(rs.getString("service"), rs.getLong("votes")));
			}
			rs.close();
			return out;
		} catch (SQLException e) {
			debug(e);
			return java.util.Collections.emptyList();
		}
	}

	private List<VoteLogEntry> query(String sql, Object[] params) {
		try (Connection conn = mysql.getConnectionManager().getConnection();
				PreparedStatement ps = conn.prepareStatement(sql)) {

			for (int i = 0; i < params.length; i++) {
				Object p = params[i];
				if (p instanceof Integer) {
					ps.setInt(i + 1, (Integer) p);
				} else if (p instanceof Long) {
					ps.setLong(i + 1, (Long) p);
				} else if (p instanceof String) {
					ps.setString(i + 1, (String) p);
				} else if (p instanceof Timestamp) {
					ps.setTimestamp(i + 1, (Timestamp) p);
				} else {
					ps.setObject(i + 1, p);
				}
			}

			ResultSet rs = ps.executeQuery();
			List<VoteLogEntry> out = Collections.synchronizedList(new java.util.ArrayList<>());

			while (rs.next()) {
				out.add(new VoteLogEntry(rs.getString("vote_id"), rs.getLong("vote_time"), rs.getString("player_uuid"),
						rs.getString("player_name"), rs.getString("service"), rs.getString("server"),
						rs.getString("event"), rs.getString("context"), rs.getString("status"),
						rs.getInt("cached_total")));
			}
			rs.close();
			return out;
		} catch (SQLException e) {
			debug(e);
			return java.util.Collections.emptyList();
		}
	}

	// ---- DTOs ----

	public static class VoteLogEntry {
		public final String voteId;
		public final long voteTime;
		public final String playerUuid;
		public final String playerName;
		public final String service;
		public final String server;
		public final String event;
		public final String context;
		public final String status;
		public final int proxyCachedTotal;

		public VoteLogEntry(String voteId, long voteTime, String playerUuid, String playerName, String service,
				String server, String event, String context, String status, int proxyCachedTotal) {
			this.voteId = voteId;
			this.voteTime = voteTime;
			this.playerUuid = playerUuid;
			this.playerName = playerName;
			this.service = service;
			this.server = server;
			this.event = event;
			this.context = context;
			this.status = status;
			this.proxyCachedTotal = proxyCachedTotal;
		}
	}

	public static class VoteLogCounts {
		public final long total;
		public final long immediate;
		public final long cached;

		public VoteLogCounts(long total, long immediate, long cached) {
			this.total = total;
			this.immediate = immediate;
			this.cached = cached;
		}
	}

	public static class ServiceCount {
		public final String service;
		public final long votes;

		public ServiceCount(String service, long votes) {
			this.service = service;
			this.votes = votes;
		}
	}
}
