package com.bencodez.votingplugin.tests.votesite;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.CALLS_REAL_METHODS;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;

import java.util.ArrayList;

import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.Test;

import com.bencodez.votingplugin.config.ConfigVoteSites;

/**
 * Tests the unfiltered configured vote-site section lookup.
 */
public class ConfigVoteSitesRawNamesTest {

	/**
	 * Creates a partially real ConfigVoteSites mock whose data comes from the
	 * supplied in-memory YAML configuration.
	 *
	 * @param data in-memory configuration data
	 * @return the configuration object
	 */
	private ConfigVoteSites configWithData(YamlConfiguration data) {
		ConfigVoteSites config = mock(ConfigVoteSites.class, CALLS_REAL_METHODS);
		doReturn(data).when(config).getData();
		doAnswer(invocation -> {
			data.set("VoteSites." + invocation.getArgument(0) + "." + invocation.getArgument(1),
					invocation.getArgument(2));
			return null;
		}).when(config).set(anyString(), anyString(), any());
		return config;
	}

	@Test
	public void testRawNamesIncludesEnabledAndDisabledSections() {
		YamlConfiguration data = new YamlConfiguration();

		data.createSection("VoteSites.EnabledSite");
		data.set("VoteSites.EnabledSite.Enabled", true);
		data.set("VoteSites.EnabledSite.ServiceSite", "enabled.example.com");

		data.createSection("VoteSites.DisabledSite");
		data.set("VoteSites.DisabledSite.Enabled", false);
		data.set("VoteSites.DisabledSite.ServiceSite", "disabled.example.com");

		ArrayList<String> names = configWithData(data).getRawVoteSiteNames();

		assertEquals(2, names.size());
		assertTrue(names.contains("EnabledSite"));
		assertTrue(names.contains("DisabledSite"),
				"Disabled sections must remain visible to existence checks");
	}

	@Test
	public void testRawNamesIgnoresMalformedScalarChildren() {
		YamlConfiguration data = new YamlConfiguration();

		data.createSection("VoteSites.RealSite");
		data.set("VoteSites.RealSite.Enabled", false);
		data.set("VoteSites.MalformedSite", "this is a scalar and not a vote-site section");

		ArrayList<String> names = configWithData(data).getRawVoteSiteNames();

		assertEquals(1, names.size());
		assertEquals("RealSite", names.get(0));
	}

	@Test
	public void testRawNamesReturnsEmptyWhenVoteSitesSectionIsMissing() {
		YamlConfiguration data = new YamlConfiguration();

		assertTrue(configWithData(data).getRawVoteSiteNames().isEmpty());
	}

	@Test
	public void testRawNamesReturnsEmptyWhenVoteSitesValueIsMalformed() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites", "not a configuration section");

		assertTrue(configWithData(data).getRawVoteSiteNames().isEmpty());
	}

	@Test
	public void markerlessLegacySiteWithMatchingKeyRemainsTrusted() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.Example%player_name%&a.ServiceSite", "Example%player_name%&a");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("Example%player_name%&a"));
		assertFalse(configWithData(data).isAutomaticallyCreatedVoteSite("Example%player_name%&a"));
	}

	@Test
	public void delimiterFreeMarkerlessLegacySiteRemainsTrusted() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.Example_com.ServiceSite", "Example.com");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("Example_com"));
		assertFalse(configWithData(data).isAutomaticallyCreatedVoteSite("Example_com"));
	}

	@Test
	public void correctedMarkerlessLegacyFallbackRemainsTrusted() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.%player_name%.ServiceSite", "corrected.example");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("%player_name%"));
		assertFalse(configWithData(data).isAutomaticallyCreatedVoteSite("%player_name%"));
	}

	@Test
	public void markerlessManualFallbackWithSafeIndependentKeyRemainsTrusted() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.Configured.ServiceSite", "corrected.example");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("Configured"));
		assertFalse(configWithData(data).isAutomaticallyCreatedVoteSite("Configured"));
	}

	@Test
	public void correctionDoesNotInventLegacyAutomaticOrigin() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.%player_name%.ServiceSite", "%player_name%");
		ConfigVoteSites config = configWithData(data);

		config.setServiceSite("%player_name%", "corrected.example");

		assertFalse(data.contains("VoteSites.%player_name%.AutoGeneratedServiceSite"));
		assertFalse(config.isAutomaticallyCreatedVoteSite("%player_name%"));
		assertFalse(config.isAutoGeneratedServiceSite("%player_name%"));
	}

	@Test
	public void legacyConfiguredSiteWithIndependentKeyRemainsTrusted() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.Configured.ServiceSite", "Example%player_name%&a");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("Configured"));
	}

	@Test
	public void explicitGenerationMarkerOverridesLegacyFallback() {
		YamlConfiguration data = new YamlConfiguration();
		data.set("VoteSites.Example%player_name%&a.ServiceSite", "Example%player_name%&a");
		data.set("VoteSites.Example%player_name%&a.AutoGeneratedServiceSite", "");

		assertFalse(configWithData(data).isAutoGeneratedServiceSite("Example%player_name%&a"));
		assertFalse(configWithData(data).isAutomaticallyCreatedVoteSite("Example%player_name%&a"));
	}
}
