package com.bencodez.votingplugin.tests.votesite;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.concurrent.TimeUnit;

import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.configuration.MemoryConfiguration;
import org.bukkit.configuration.file.YamlConfiguration;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import com.bencodez.advancedcore.api.rewards.RewardBuilder;
import com.bencodez.advancedcore.api.rewards.RewardDisplayPlaceholders;
import com.bencodez.simpleapi.time.ParsedDuration;
import com.bencodez.votingplugin.VotingPluginMain;
import com.bencodez.votingplugin.config.Config;
import com.bencodez.votingplugin.config.ConfigVoteSites;
import com.bencodez.votingplugin.data.ServerData;
import com.bencodez.votingplugin.votesites.VoteSite;

public class VoteSiteTest {

	private VotingPluginMain plugin;

	@BeforeEach
	public void setUp() {
		plugin = mock(VotingPluginMain.class);

		ConfigVoteSites dummyConfigVoteSites = mock(ConfigVoteSites.class);
		when(dummyConfigVoteSites.getVoteURL(anyString())).thenReturn("example.com");
		when(dummyConfigVoteSites.getServiceSite(anyString())).thenReturn("ServiceSite");
		when(dummyConfigVoteSites.getVoteDelay(anyString())).thenReturn(ParsedDuration.parse("12h", TimeUnit.HOURS));
		when(dummyConfigVoteSites.getVoteSiteEnabled(anyString())).thenReturn(true);
		when(dummyConfigVoteSites.getPriority(anyString())).thenReturn(1);
		when(dummyConfigVoteSites.getDisplayName(anyString())).thenReturn("DisplayName");
		when(dummyConfigVoteSites.getItem(anyString())).thenReturn(null);

		Config dummyConfigFile = mock(Config.class);
		when(dummyConfigFile.isFormatCommandsVoteForceLinks()).thenReturn(true);

		ServerData dummyServerData = mock(ServerData.class);
		when(dummyServerData.getServiceSites())
				.thenReturn(new ArrayList<>(Arrays.asList("ServiceSite", "AnotherSite")));

		when(plugin.getConfigVoteSites()).thenReturn(dummyConfigVoteSites);
		when(plugin.getConfigFile()).thenReturn(dummyConfigFile);
		when(plugin.getServerData()).thenReturn(dummyServerData);
	}

	@Test
	public void testInitSetsValuesCorrectly() {
		VoteSite voteSite = new VoteSite(plugin, "site.test");

		assertEquals("site_test", voteSite.getKey(), "Key should have dots replaced with underscores");
		assertEquals("DisplayName", voteSite.getDisplayName(), "Display name should be loaded from config");
		assertEquals("example.com", voteSite.getVoteURL(false), "VoteURL should be set from config");
		assertEquals("ServiceSite", voteSite.getServiceSite(), "ServiceSite should be set from config");
		assertTrue(voteSite.isEnabled(), "VoteSite should be enabled");

		ParsedDuration d = voteSite.getVoteDelay();
		assertEquals(12L * 60L * 60L * 1000L, d.getMillis(), "VoteDelay millis should be 12h");
	}

	@Test
	public void serviceSiteFormattingCannotJoinSurroundingColorCodes() {
		VoteSite voteSite = new VoteSite(plugin, "site.test");

		assertEquals("ServiceSite", voteSite.getServiceSiteForFormatting().replace("\u2060", ""));
		assertTrue(("&" + voteSite.getServiceSiteForFormatting()).indexOf("&S") < 0);
	}

	@Test
	public void rewardActionsPreserveOrdinaryServiceSiteExactly() throws Exception {
		VoteSite voteSite = new VoteSite(plugin, "site.test");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);

		assertEquals("ServiceSite", builder.getRewardOptions().getPlaceholders().get("ServiceSite"));
		assertEquals("ServiceSite", RewardDisplayPlaceholders
				.forDisplay(builder.getRewardOptions().getPlaceholders()).get("ServiceSite").replace("\u2060", ""));
	}

	@Test
	public void rewardActionsBreakExternallySuppliedPlaceholderAndColorTokens() throws Exception {
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("%player_name%&aGreen");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		when(plugin.getConfigVoteSites().isAutomaticallyCreatedVoteSite(anyString())).thenReturn(true);
		when(plugin.getConfigVoteSites().getDisplayName(anyString())).thenReturn("");
		VoteSite voteSite = new VoteSite(plugin, "%player_name%&aGreen");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);
		String serviceAction = builder.getRewardOptions().getPlaceholders().get("ServiceSite");
		String siteAction = builder.getRewardOptions().getPlaceholders().get("SiteName");

		assertTrue(!serviceAction.contains("%player_name%"));
		assertTrue(!serviceAction.contains("&aGreen"));
		assertTrue(!siteAction.contains("%player_name%"));
		assertTrue(!siteAction.contains("&aGreen"));
		assertEquals("%player_name%&aGreen", serviceAction.replace("\u2060", ""));
		assertEquals("%player_name%&aGreen", siteAction.replace("\u2060", ""));
	}

	@Test
	public void rewardActionsGuardDelimiterFreeValuesOnlyWhenTemplateCompletesTokens() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console", java.util.List.of("say %%ServiceSite%% &%SiteName%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("player_name");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		when(plugin.getConfigVoteSites().isAutomaticallyCreatedVoteSite(anyString())).thenReturn(true);
		when(plugin.getConfigVoteSites().getDisplayName(anyString())).thenReturn("");
		VoteSite voteSite = new VoteSite(plugin, "aGreen");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);
		String service = builder.getRewardOptions().getPlaceholders().get("ServiceSite");
		String site = builder.getRewardOptions().getPlaceholders().get("SiteName");

		assertEquals("player_name", service);
		assertEquals("aGreen", site);
		java.lang.reflect.Field dataField = RewardBuilder.class.getDeclaredField("data");
		dataField.setAccessible(true);
		ConfigurationSection isolated = (ConfigurationSection) dataField.get(builder);
		assertEquals(java.util.List.of("say %\u2060%ServiceSite%% &\u2060%SiteName%"),
				isolated.getStringList("Rewards.Commands.Console"));
	}

	@Test
	public void unsafeTemplateDoesNotChangeSafeSiblingArgument() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console",
				java.util.List.of("unsafe %%ServiceSite%", "integration lookup %ServiceSite%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("player_name");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		VoteSite voteSite = new VoteSite(plugin, "site");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);
		java.lang.reflect.Field dataField = RewardBuilder.class.getDeclaredField("data");
		dataField.setAccessible(true);
		ConfigurationSection isolated = (ConfigurationSection) dataField.get(builder);

		assertEquals(java.util.List.of("unsafe %\u2060%ServiceSite%", "integration lookup %ServiceSite%"),
				isolated.getStringList("Rewards.Commands.Console"));
		assertEquals("player_name", builder.getRewardOptions().getPlaceholders().get("ServiceSite"));
	}

	@Test
	public void adjacentPlaceholdersRemainExactWhileEarlierOpenTokenIsGuarded() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console", java.util.List.of(
				"adjacent %SiteName%%ServiceSite%", "unsafe %player_%ServiceSite%%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("name");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		VoteSite voteSite = new VoteSite(plugin, "site");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);
		java.lang.reflect.Field dataField = RewardBuilder.class.getDeclaredField("data");
		dataField.setAccessible(true);
		ConfigurationSection isolated = (ConfigurationSection) dataField.get(builder);

		assertEquals(java.util.List.of(
				"adjacent %SiteName%%ServiceSite%", "unsafe %player_\u2060%ServiceSite%%"),
				isolated.getStringList("Rewards.Commands.Console"));
	}

	@Test
	public void ordinaryLegacyActionValueRemainsByteExactWithoutUnsafeTemplateBoundary() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console", java.util.List.of("say %ServiceSite%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("Example.com");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		VoteSite voteSite = new VoteSite(plugin, "Example_com");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);

		assertEquals("Example.com", builder.getRewardOptions().getPlaceholders().get("ServiceSite"));
	}

	@Test
	public void benignExternalDelimitersRemainExactInRewardActions() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console", java.util.List.of("integration lookup %ServiceSite%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString()))
				.thenReturn("site%20name?x=1&source=proxy");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		VoteSite voteSite = new VoteSite(plugin, "site");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);

		assertEquals("site%20name?x=1&source=proxy",
				builder.getRewardOptions().getPlaceholders().get("ServiceSite"));
	}

	@Test
	public void externalPlaceholderFragmentCannotUseTemplateSuffix() throws Exception {
		YamlConfiguration data = new YamlConfiguration();
		data.set("Rewards.Commands.Console",
				java.util.List.of("unsafe %ServiceSite%%", "unsafe extended %ServiceSite%name%",
						"integration lookup %ServiceSite%"));
		when(plugin.getConfigVoteSites().getData()).thenReturn(data);
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("%player_");
		when(plugin.getConfigVoteSites().isAutoGeneratedServiceSite(anyString())).thenReturn(true);
		VoteSite voteSite = new VoteSite(plugin, "site");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);

		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);
		java.lang.reflect.Field dataField = RewardBuilder.class.getDeclaredField("data");
		dataField.setAccessible(true);
		ConfigurationSection isolated = (ConfigurationSection) dataField.get(builder);

		assertEquals(java.util.List.of(
				"unsafe %ServiceSite%\u2060%", "unsafe extended %ServiceSite%\u2060name%",
				"integration lookup %ServiceSite%"),
				isolated.getStringList("Rewards.Commands.Console"));
	}

	@Test
	public void configuredServiceSiteRemainsExactInRewardActions() {
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("Configured%Service%&Value");
		VoteSite voteSite = new VoteSite(plugin, "site.test");

		assertEquals("Configured%Service%&Value", voteSite.getServiceSiteForActions());
	}

	@Test
	public void configuredDisplayNameRemainsExactInRewardActions() {
		VoteSite voteSite = new VoteSite(plugin, "site.test");
		voteSite.setDisplayName("Configured %server_name%");
		assertEquals("Configured %server_name%", voteSite.getDisplayNameForActions());
	}

	@Test
	public void correctedLegacyServiceStillGuardsExternalFallbackName() {
		when(plugin.getConfigVoteSites().getServiceSite(anyString())).thenReturn("corrected.example");
		when(plugin.getConfigVoteSites().isAutomaticallyCreatedVoteSite(anyString())).thenReturn(true);
		when(plugin.getConfigVoteSites().getDisplayName(anyString())).thenReturn("");
		VoteSite voteSite = new VoteSite(plugin, "%player_name%");

		assertEquals("corrected.example", voteSite.getServiceSiteForActions());
		assertTrue(!voteSite.getDisplayNameForActions().contains("%player_name%"));
		assertEquals("%player_name%", voteSite.getDisplayNameForActions().replace("\u2060", ""));
	}

	@Test
	public void manualFallbackNameRemainsExactInRewardActions() {
		when(plugin.getConfigVoteSites().getDisplayName(anyString())).thenReturn("");
		VoteSite voteSite = new VoteSite(plugin, "Manual%server_name%&a");

		assertEquals("Manual%server_name%&a", voteSite.getDisplayNameForActions());
	}

	@Test
	public void fallbackDisplayNameStaysRawForActionsAndGuardedForFormatting() throws Exception {
		when(plugin.getConfigVoteSites().getDisplayName(anyString())).thenReturn("");
		VoteSite voteSite = new VoteSite(plugin, "site.test");
		java.lang.reflect.Method factory = VoteSite.class.getDeclaredMethod("createRewardBuilder", String.class,
				boolean.class, boolean.class);
		factory.setAccessible(true);
		RewardBuilder builder = (RewardBuilder) factory.invoke(voteSite, "Rewards", true, false);

		assertEquals("site_test", voteSite.getDisplayName());
		assertEquals("site_test", builder.getRewardOptions().getPlaceholders().get("SiteName"));
		assertEquals("site_test", voteSite.getDisplayNameForFormatting().replace("\u2060", ""));
		assertTrue(voteSite.getDisplayNameForFormatting().startsWith("\u2060"));
		assertEquals(voteSite.getDisplayNameForFormatting(), RewardDisplayPlaceholders
				.forDisplay(builder.getRewardOptions().getPlaceholders()).get("SiteName"));

		voteSite.setDisplayName("Configured %server_name%");
		assertEquals("Configured %server_name%", voteSite.getDisplayNameForFormatting());
	}

	@Test
	public void testGetVoteURLJson() {
		VoteSite voteSite = new VoteSite(plugin, "site.test");
		String url = voteSite.getVoteURL(true);
		assertEquals("[Text=\"example.com\",url=\"http://example.com\"]", url,
				"JSON-formatted vote URL should be generated correctly");
	}

	@Test
	public void testLoadingDebugContainsExpectedValues() {
		VoteSite voteSite = new VoteSite(plugin, "site.test");
		String debug = voteSite.loadingDebug();

		assertTrue(debug.contains("site_test"), "Debug output should contain the key");
		assertTrue(debug.contains("DisplayName"), "Debug output should contain the display name");

		// New system: no VoteDelayMin in debug output
		assertTrue(!debug.toLowerCase().contains("votedelaymin"), "Debug output should not contain VoteDelayMin");

		// Depending on how you stringify VoteDelay, accept either "12h" or raw millis
		// value
		assertTrue(debug.contains("12h") || debug.contains("43200000"),
				"Debug output should contain the vote delay (12h or 43200000ms)");
	}

	// -------------------------------------------------------------------------
	// Legacy conversion tests (old style VoteDelay + VoteDelayMin ->
	// ParsedDuration)
	// -------------------------------------------------------------------------

	@Test
	public void testConvertLegacyHoursOnly() {
		MemoryConfiguration cfg = new MemoryConfiguration();
		ConfigurationSection sec = cfg.createSection("Site");
		sec.set("VoteDelay", 24); // legacy numeric hours

		ParsedDuration d = parseVoteDelayWithLegacySupport(sec);

		assertEquals(24L * 60L * 60L * 1000L, d.getMillis(), "24 hours should convert to millis correctly");
	}

	@Test
	public void testConvertLegacyHoursAndMinutes() {
		MemoryConfiguration cfg = new MemoryConfiguration();
		ConfigurationSection sec = cfg.createSection("Site");
		sec.set("VoteDelay", 24); // hours
		sec.set("VoteDelayMin", 30); // minutes

		ParsedDuration d = parseVoteDelayWithLegacySupport(sec);

		long expected = (24L * 60L * 60L * 1000L) + (30L * 60L * 1000L);
		assertEquals(expected, d.getMillis(), "24h + 30m should convert to millis correctly");
	}

	@Test
	public void testConvertLegacyMinutesOnly() {
		MemoryConfiguration cfg = new MemoryConfiguration();
		ConfigurationSection sec = cfg.createSection("Site");
		sec.set("VoteDelay", 0); // legacy requirement: VoteDelay exists
		sec.set("VoteDelayMin", 45); // minutes-only

		ParsedDuration d = parseVoteDelayWithLegacySupport(sec);

		long expected = 45L * 60L * 1000L;
		assertEquals(expected, d.getMillis(), "0h + 45m should convert to millis correctly");
	}

	@Test
	public void testNewStringFormatTakesPrecedenceOverLegacy() {
		MemoryConfiguration cfg = new MemoryConfiguration();
		ConfigurationSection sec = cfg.createSection("Site");

		// Both provided; string should win
		sec.set("VoteDelay", "1h30m");
		sec.set("VoteDelayMin", 999); // should be ignored in new format

		ParsedDuration d = parseVoteDelayWithLegacySupport(sec);

		long expected = (1L * 60L * 60L * 1000L) + (30L * 60L * 1000L);
		assertEquals(expected, d.getMillis(), "String VoteDelay should override legacy VoteDelayMin");
	}

	@Test
	public void testEmptyOrMissingVoteDelayReturnsEmpty() {
		MemoryConfiguration cfg = new MemoryConfiguration();
		ConfigurationSection sec = cfg.createSection("Site");

		ParsedDuration d = parseVoteDelayWithLegacySupport(sec);
		assertTrue(d == null || d.isEmpty() || d.getMillis() == 0L,
				"Missing VoteDelay should result in empty/zero delay");
	}

	/**
	 * Test helper that mirrors the intended production behavior: - If VoteDelay is
	 * a string -> ParsedDuration.parse(...) - Else legacy numeric VoteDelay (hours)
	 * + VoteDelayMin (minutes) -> millis
	 *
	 * NOTE: months are intentionally ignored by the rest of your code, but this
	 * conversion does not create months unless the string contains 'mo'.
	 */
	private static ParsedDuration parseVoteDelayWithLegacySupport(ConfigurationSection sec) {
		if (sec == null) {
			return ParsedDuration.ofMillis(0);
		}

		if (sec.isString("VoteDelay")) {
			String s = sec.getString("VoteDelay", "");
			if (s == null || s.trim().isEmpty()) {
				return ParsedDuration.ofMillis(0);
			}
			return ParsedDuration.parse(s, TimeUnit.HOURS);
		}

		// Legacy numeric style
		double hours = sec.getDouble("VoteDelay", 0D);
		double minutes = sec.getDouble("VoteDelayMin", 0D);

		long millis = (long) (hours * 60D * 60D * 1000D) + (long) (minutes * 60D * 1000D);
		return ParsedDuration.ofMillis(millis);
	}
}
