name: ${project.name}
version: ${project.version}
main: com.Ben12345rocks.VotingPlugin.Main
description: Highly Customizable Voting Listener!
website: https://www.spigotmc.org/resources/votingplugin.15358/
author: Ben12345rocks
softdepend: [MVdWPlaceholders, Votifier, CMI, Vault, PlaceholderAPI, ProtocolLib]
api-version: 1.13
commands:
  vote:
    description: Vote command
  adminvote:
    description: Admin commands for VotingPlugin
  av:
    description: Admin commands for VotingPlugin
  votehelp:
    description: See access to a list of commands, Formated in Format.yml
    aliases: vhelp
  votetotal:
    description: See totals of votes
    aliases: vtotal
  votelast:
    description: See the last time you voted
    aliases: vlast
  votenext:
    description: See when you can vote next
    aliases: vnext
  votetop:
    description: See top voters
    aliases: vtop
  votetoday:
    description: See who voted today
    aliases: vtoday
  votegui:
    description: Open VoteGUI
    aliases: vgui
  voteurl:
    description: Open VoteURL
    aliases: vurl
  votereward:
    description: Open VoteReward GUI
    aliases: vreward
  vote?:
    description: View Help
    aliases: v?
  voteparty:
    description: A command
    aliases: vparty
  voteshop:
    description: A command
    aliases: vshop
  votebest:
    description: A command
    aliases: vbest
  votestreak:
    description: A command
    aliases: vstreak
  votetogglebroadcast:
    description: A command
    aliases: vtogglebroadcast
  votepoints:
    description: A command
    aliases: vpoints
  votelist:
    description: A command
    aliases: vlist
  voteall:
    description: A command
    aliases: vall
  votechoices:
    description: A command
    alaises: vchoices
  votegivepoints:
    description: A command
    alaises: vgivepoints
  adminvotehelp:
    description: Open adminvote help
    aliases: avhelp
  adminvote?:
    description: Open adminvote help
    aliases: av?
  adminvotereport:
    description: Command Alias
    aliases: avreport
  adminvoteperms:
    description: Command Alias
    aliases: avperms
  adminvoteDownload:
    description: Command Alias
    aliases: avdownload
  adminvotereload:
    description: Command Alias
    aliases: avreload
  adminvotetestreward:
    description: Command Alias
    aliases: avtestreward
  adminvoteversion:
    description: Command Alias
    aliases: avversion
  adminvotesites:
    description: Command Alias
    aliases: avsites
  adminvoterewards:
    description: Command Alias
    aliases: avrewards
  adminvoteuuid:
    description: Command Alias
    aliases: avuuid
  adminvotevotesite:
    description: Command Alias
    aliases: avvotesite
  adminvoteconfig:
    description: Command Alias
    aliases: avconfig
  adminvotesettotal:
    description: Command Alias
    aliases: avsettotal
  adminvoteupdatecheck:
    description: Command Alias
    aliases: avupdatecheck
  adminvotevote:
    description: Command Alias
    aliases: [avvote, fakevote]
  adminvotegui:
    description: Command Alias
    aliases: avgui
  adminvotegivereward:
    description: Command Alias
    aliases: avgivereward
  adminvoteusers:
    description: Command Alias
    aliases: avusers
  adminvoteConvertFromData:
    description: Command Alias
    aliases: avConvertFromData
  adminvoteClearTotal:
    description: Command Alias
  adminvoteBackgroundUpdate:
    description: Command Alias
    aliases: avBackgroundUpdate
  adminvoteClearCache:
    description: Command Alias
    aliases: avClearCache
  adminvoteConvertFrom:
    description: Command Alias
    aliases: avConvertFrom
  adminvoteServiceSites:
    description: Command Alias
    aliases: avServiceSites
  adminvoteSetVotePartyCount:
    description: Command Alias
    aliases: avSetVotePartyCount
  adminvoteClearOfflineVotes:
    description: Command Alias
    aliases: avClearOfflineVotes
  adminvoteGiveAll:
    description: Command Alias
    aliases: avGiveAll
  adminvoteGiveAllOnline:
    description: Command Alias
    aliases: avGiveAllOnline
  adminvoteForceTimeChanged:
    description: Command Alias
    aliases: avForceTimeChanged
  adminvoteplayername:
    description: Command Alias
    aliases: avplayername
  adminvoteResyncMilestones:
    description: Command Alias
    aliases: avResyncMilestones
  adminvoteClearOfflineRewards:
    description: Command Alias
    aliases: avClearOfflineRewards
  adminvoteUserRemove:
    description: Command Alias
    aliases: avUserRemove
  adminvotePurge:
    description: Command Alias
    aliases: avPurge
  adminvoteJavascript:
    description: Command Alias
    aliases: avJavascript
  adminvoteStatus:
    description: Command Alias
    aliases: avStatus
  adminvoteTest:
    description: Command Alias
    aliases: avTest
  adminvotePlaceholders:
    description: Command Alias
    aliases: avPlaceholders
  adminvoteDownloadJenkins:
    description: Command Alias
    aliases: avDownloadJenkins
  adminvoteForceVoteParty:
    description: Command Alias
    aliases: avForceVoteParty
  adminvoteUserEditValue:
    description: Command Alias
    aliases: avUserEditValue
  adminvoteSetRequestMethod:
    description: Command Alias
    aliases: avSetRequestMethod
  adminvoteUser:
    description: Command Alias
    aliases: avUser
permissions:
  VotingPlugin.Player:
    description: Allows basic access player commands
  VotingPlugin.Mod:
    description: Allows mod access player commands
  VotingPlugin.Admin:
    description: Allows admin access player commands
  VotingPlugin.Login.RemindVotes:
    description: Allows players to get remined on login if they can vote
    default: true
  VotingPlugin.Admin.Debug:
    description: Permission to view debug info ingame
  VotingPlugin.Signs.Create:
    description: Allows access to create signs
  VotingPlugin.TopVoter.Ignore:
    description: Allows you to be exempt from top voter
  VotingPlugin.NoRemind:
    description: Ignore vote reminding
    default: false
  VotingPlugin.Sign.Create:
    description: Permission to create sign
  VotingPlugin.Admin.GenerateServiceSite:
    description: Permission for generating votesite message
  